### ISSUE TITLE
Feature request: dashesOnly support

### ISSUE THREAD

**Issue by mixedCase** [css-modules/postcss-modules#93]
css-loader supports a `camelCase` setting of value `dashesOnly`, where dashes are substituted by camel casing the next word, but underscores are left untouched, which is subjectively a very nice combination with the BEM naming convention.

Would be great to have this option in postcss-modules.

**Comment by allocenx** [comment]
Yes this has to be a must! Any idea when we will have this???

**Comment by outpunk** [comment]
@mixedCase agreed, that can be useful. 
@mixedCase @allocenx Do you guys want to make a PR?

**Comment by allocenx** [comment]
Hello @outpunk, yes, I will make a PR these days. Thank you :)

**Comment by outpunk** [comment]
Awesome, looking forward!

**Comment by allocenx** [comment]
@outpunk, please take a look and if all good please merge it otherwise lemme know what else is to be done. I need this feature ASAP on one of my projects which is urgent and update the NPM package too so I can fetch the last version after the merge.

Also, is there a possibility, I can make another PR with a refactored code?

**Comment by outpunk** [comment]
Thanks @allocenx! Released in [2.0.0](https://github.com/css-modules/postcss-modules/blob/master/CHANGELOG.md#200)
